# fly.toml app configuration file generated for mikesreadinglist on 2023-04-28T17:02:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mikesreadinglist"
primary_region = "iad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
